apiVersion: v1
kind: Service
metadata:
  name: devops41-service
spec:
  type: NodePort
  selector:
    app: devops41
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001